[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs']  # Thêm 'nodejs' để cài Node.js và npm

[phases.build]
cmds = [
    'composer install',              # Cài dependency PHP
    'npm install',                   # Cài dependency Node.js
    'npm run build',                 # Build tài nguyên frontend (thay bằng 'npm run dev' nếu cần)
    'php artisan key:generate',      # Tạo APP_KEY
    'php artisan migrate --force'    # Chạy migration
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'